blank_issues_enabled: false
contact_links:
  - name: ثبت مدل یا دیتاست جدید
    url: https://amiralifirouzi.github.io/zal
    about: برای ثبت مدل زبانی یا دیتاست فارسی خود، لطفاً به وب‌سایت زال مراجعه کرده و از دکمه‌ی «ثبت مدل یا دیتاست» استفاده کنید.
